### ISSUE TITLE
Egregious analysis errors in the generative methodology

### ISSUE THREAD

**Issue by MarcioPais** [google-deepmind/language_modeling_is_compression#9] opened 2024-01-21 13:33 UTC
This "issue" pertains to the original version of the paper as posted to Arxiv.

A modified version submitted to ICLR 2024 has at least removed some of the nonsense, not to address the fundamental lapse in judgement, but at the request of reviewers on OpenReview, who are just as clueless.

A detailed analysis of the problem can be found [here](https://encode.su/threads/4186-Getting-Lossless-Compression-Adopted-For-Rigorous-LLM-Benchmarking).

Suffice it to say that it's inconstruable how anyone with even just a mild understanding of information theory can look at the listed "gzip Samples" in Fig. 3, page 9 of the original paper, and say to themselves "_Yes, these completely gibberish, almost random looking like sequences seem about right for what such a simplistic and limited compression method as that used in gzip would find the MOST easy to compress after being given the previous context-text_". Seriously?

That **12** people felt confortable signing off on this travesty says everything one needs to know about the current state of research.

Feel free to delete this issue instead of addressing it, I'd expect nothing less.

**Comment by fazega** [comment] 2024-01-22 13:48
Hello,
Section 3.4 indeed exposes 'naive' auto-regressive sampling, i.e. sampling with a horizon of 1 as it is currently done with language models. We agree with you that this version is not optimal, in the sense that without consistency guarantee (i.e. P(x_1...K) = sum_y P(x_1...K y)) you are not guaranteed to find good continuations by just sampling the next byte. Intuitively, as you pointed out, the problem is that longer continuations (internal 'tokens' in the case of gzip) will have lower probability but will (likely) not be found by 1-step autoreg sampling. We will add a remark about this in the next revision of the paper. Note that we still explicitly say in this section 'Theoretically, there is no strong guarantee that a good compression rate leads to “good” autoregressive samples'. Also note that this problem was extensively studied in [this paper](https://arxiv.org/abs/1407.3334) by Marcus in 2014, that we will cite in the next revision.

**Comment by fazega** [comment] 2024-01-22 13:49
Closing.

**Closed as completed by fazega** 2024-01-22 13:49 UTC
